# Generated by Django 4.1.7 on 2023-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255)),
                ('character_class', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=255)),
                ('shoulders', models.CharField(max_length=255)),
                ('chest', models.CharField(max_length=255)),
                ('gloves', models.CharField(max_length=255)),
                ('legs', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('total_tier', models.IntegerField()),
            ],
        ),
    ]
